### ISSUE TITLE
debezium-connector-sqlserver NOT compiling

### ISSUE THREAD

**Issue by Sano123456** [debezium/debezium-incubator#35]
I am tring to compile this plugin to add it to confluent but it give me error

[ERROR] /opt/test/debezium-incubator/debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SourceInfo.java:[98,5] method does not override or implement a method from a supertype
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.433 s
[INFO] Finished at: 2018-10-10T10:58:20+00:00
[INFO] Final Memory: 34M/382M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project debezium-connector-sqlserver: Compilation failure
[ERROR] /opt/test/debezium-incubator/debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SourceInfo.java:[98,5] method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

let me know how to solve it

**Comment by Sano123456** [comment]
Yes I am using the last one I made a clone of repository just yesterday

**Comment by jpechane** [comment]
I cannot confirm the problem. I've checked out latest master on debezium/debezium repository - commit bc0712e2408e10ca8c23985bbaf71e2fc1438b0c
Executed `mvn clean install -DskipTests -DskipITs`
Then I checkout out latest master on debezium/debezium-incubator - commit 1590534b975b0e302dd3a2d85b915f71fe8178bf
Executed `mvn clean install -DskipTests -DskipITs`

Evertyhing compiled

**Comment by Sano123456** [comment]
if you like i can make a video to show the process i am doing, below commands i am using
git clone https://github.com/debezium/debezium-incubator.git
cd debezium-incubator
mvn clean install -DskipTests -DskipITs
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:checkstyle (check-style) on project debezium-incubator-parent: Execution check-style of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:checkstyle failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.15 or one of its dependencies could not be resolved: Failure to find io.debezium:debezium-checkstyle:jar:0.9.0-SNAPSHOT in http://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]
cd debezium-connector-sqlserver
mvn clean install -DskipTests -DskipITs
[ERROR] /opt/test/debezium-incubator/debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SourceInfo.java:[98,5] method does not override or implement a method from a supertype


all i need is the sqlserver connector
let me kow

**Comment by jpechane** [comment]
I see but the message is self-explanatory - you *MUST* build the content of debezium/debezium repository first as it contains `core` and other modules on which it depends.

**Comment by Sano123456** [comment]
but i already have them installed, if i put them in JAVA_HOME it may can resolve the dependecy or i need recompile debezium/debezium  anyway ?

**Comment by jpechane** [comment]
You need to recompile it to fill your Maven local repository.

**Comment by Sano123456** [comment]
sorry i need to understand something, why the project pom point to ${project.version} forcing to ecompile the code instead of using public repository like this one? 


<dependency>
    <groupId>io.debezium</groupId>
    <artifactId>debezium-core</artifactId>
    <version>0.8.3.Final</version>
</dependency>


can i use the public repo for this?

**Comment by jpechane** [comment]
You are working with snapshot version and it depends on the changes done in snapshot version of the main repository. Sometimes it is necessary to modyf the core with fetures required be the incubating connectors. And such features might not be released in non-nspashot repository yet.

**Comment by Sano123456** [comment]
ok thanks very much, all solved, i need recompile the core
thanks very much
