### ISSUE TITLE
Multiple Debezium Connector config for SQL Server

### ISSUE THREAD

**Issue by pradeepmvn** [debezium/debezium-incubator#44]
Question:
Can one instance of [debezium Docker](https://hub.docker.com/r/debezium/connect/) container execute multiple SQLServer connectors pointing to the different databases?

I tried to start 2 connectors to 2 different databases with 1 connect instance running. The first connector gets messed up and fails, but the second one keeps running.  Any suggestions?

**Comment by gunnarmorling** [comment]
Hi, please use the [mailing list](https://groups.google.com/forum/#!forum/debezium) for these kinds of questions, as this issue tracker isn't the right place to get help. To answer the question, you definitely should be able to deploy multiple connector instances. Can you please send a mail to the list showing the failure / stack trace from the first connector? Thanks!
