### ISSUE TITLE
debezium 对接oracle 11G问题

### ISSUE THREAD

**Issue by RunningXuan** [debezium/debezium-incubator#75]
使用debezium0.9.2 oracleconnect 连接oracle11G,不能正常获取数据，配置如下：
name:oracleconect
connector.class:io.debezium.connector.oracle.OracleConnector
tasks.max:1
database.hostname:111.132.15.1
database.port:1521
database.user:xstrmuser
database.password:123456
database.sid:orcl
database.dbname:dbawork
database.pdb.name:dbawork
database.tablename.case.insensitive:true
database.oracle.version:11
table.whitelist:dbawork.t_user
database.out.server.name:dbzxout
database.server.name:oracle
database.history.kafka.bootstrap.servers:192.168.0.155:9092
database.history.kafka.topic:oracle.schema

配置文件有问题吗？，如果是11G database.dbname 和pdb.name 应该怎么配置呢？

**Comment by jpechane** [comment]
Hi,

unfortunately we are not able to understand the issue. Is it a bug report? If yes please use https://issues.jboss.org/projects/DBZ/issues to raise the issue. If it is a question lease join our Gitter chat or mailing list https://groups.google.com/forum/?fromgroups=#!forum/debezium

Thanks for understanding

J.
